### ISSUE TITLE
Pb parsing

### ISSUE THREAD

**Issue by JFredPerspektiv** [anisayari/easy_facial_recognition#1]
Bonjour Anis, 
Je suis débutant en OpenCV, et j'aimerais mettre en oeuvre votre prog. 
Pouvez-vous m'aider svp?
J'ai essayé plusieurs fois d'exécuter  avec 'easy_facial_recognition.py --i known_faces', mais après avoir résolu les pb de modules (incompatibilités), j'ai ce nouveau message d'erreur:

easy_facial_recognition.py --i known_faces
  File "<ipython-input-6-f06bc76b4e6d>", line 1
    easy_facial_recognition.py --i known_faces
                                             ^
SyntaxError: invalid syntax

=> Si j'exécute le prog depuis Spyder, j'obtiens:
runfile('/home/jfred/easy_facial_recognition-master/easy_facial_recognition.py', wdir='/home/jfred/easy_facial_recognition-master')
[INFO] Starting System...
[INFO] Importing pretrained model..
[INFO] Importing pretrained model..
usage: easy_facial_recognition.py [-h] -i INPUT
easy_facial_recognition.py: error: the following arguments are required: -i/--input
An exception has occurred, use %tb to see the full traceback.

=> En tapant %tb, j'obtiens: 

SystemExit: 2

Traceback (most recent call last):

  File "/home/jfred/easy_facial_recognition-master/easy_facial_recognition.py", line 83, in <module>
    args = parser.parse_args()

  File "/home/jfred/anaconda3/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)

  File "/home/jfred/anaconda3/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)

  File "/home/jfred/anaconda3/lib/python3.7/argparse.py", line 2022, in _parse_known_args
    ', '.join(required_actions))

  File "/home/jfred/anaconda3/lib/python3.7/argparse.py", line 2508, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

  File "/home/jfred/anaconda3/lib/python3.7/argparse.py", line 2495, in exit
    _sys.exit(status)

SystemExit: 2

**Comment by anisayari** [comment]
Il faut appeler un script python avec la commande python depuis le terminal donc 

`easy_facial_recognition.py --i known_faces`
en
`python3 easy_facial_recognition.py --i known_faces`

**Comment by JFredPerspektiv** [comment]
Bonjour Anis,
Un grand merci pour cette réponse. Et mille fois navré de ma réponse
tardive!
J'avais bien essayé l'instruction indiquée, mais le prog plante idem sur le
PC Windows et aussi sur celui installé en Ubuntu spécialement. Je continué
à étudier le Python, et je retravaillerai sur votre prog la semaine
prochaine.
Bien cordialement, JFred

Le ven. 17 juil. 2020 à 18:19, Anis AYARI <notifications@github.com> a
écrit :

**Comment by anisayari** [comment]
Aucune nouvelle sur l'erreur, je la ferme, n'hésite pas à la réouvrir si il y a du nouveau.

**Comment by JFredPerspektiv** [comment]
Oui, merci Anis pour tes conseils, j'ai peut-être compris pourquoi cela ne
fonctionnait pas: au final, je crois que c'est l'instruction pour importer
PILLOW qui ne fonctionnait pas...
Désolé, je suis parti à Taiwan, et ai eu mille choses à faire ! Je suis en
train de ré-installer toutes la suites IA et robotique sur ce PC, et vais
m'y remettre.
Très bonne journée !

Le mer. 16 déc. 2020 à 19:06, Anis AYARI <notifications@github.com> a
écrit :
